### PR TITLE
Update Python wrapper to upstream Feb 2022

### PR DESCRIPTION
**Pull request by johnwason**
This pull request updates the Python wrappers as of Feb 2022.

TODO: Update dependencies.rosinstall before merging!!

### CODE REVIEW

**Comment by johnwason** [comment]
@Levi-Armstrong this should be ready once the forks in tesseract and tesseract_planning are accepted.

https://github.com/tesseract-robotics/tesseract/pull/716
https://github.com/tesseract-robotics/tesseract_planning/pull/172

**Comment by Levi-Armstrong** [comment]
I left a few comments, but should be able to get them merged this week.

**Comment by johnwason** [comment]
I have a project meeting Tuesday afternoon so I'd like to have it read by then. I'll fix the remaining issues tonight.

**Comment by johnwason** [comment]
All checks in the other pull requests are passing

**Comment by Levi-Armstrong** [comment]
Both dependency repos have been merged.

**Comment by johnwason** [comment]
I've updated the dependencies files. Once the CI has finished I will merge.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by johnwason** [comment]
I think it would make sense to wait for https://github.com/tesseract-robotics/tesseract/pull/717 to be merged and update dependencies again before merging

**Pull request merged**
